version: "3"
services:
    web:
        build: 
            context: .
            dockerfile: CountryApi/Dockerfile
        image: country-api
        env_file: 
            - web.env
        volumes:
            - countryApi-data:/app/Logs
        ports:
            - "8080:80"
        entrypoint: ["dotnet", "CountryApi.dll"]
volumes:
    countryApi-data:
        external: true