name: CountryApi CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET Core SDK
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Navigate to the project directory and restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./CountryApi/CountryApi/CountryApi.csproj

      - name: Clean previous builds
        run: dotnet clean ./CountryApi/CountryApi/CountryApi.csproj --configuration Release

      # Build the project
      - name: Build the project
        run: dotnet build ./CountryApi/CountryApi/CountryApi.csproj --configuration Release --no-restore

      # Publish the build
      - name: Publish the project
        run: dotnet publish ./CountryApi/CountryApi/CountryApi.csproj -c Release -o ./publish

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (or another registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./CountryApi
          file: ./CountryApi/CountryApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/countryapi:latest
          
