name: ASP.NET Core Web API CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x' # Change to your .NET version

    # Install dependencies
    - name: Install dependencies
      run: dotnet restore

    # Build the project
    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Run unit tests
    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Publish the application
    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./publish

    # Archive the publish folder
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: api-publish
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: api-publish

    # Deploy the application (e.g., to Azure or any hosting provider)
    # Uncomment and customize the following steps based on your hosting provider
    # - name: Deploy to Azure
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'your-app-name'
    #     slot-name: 'production'
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #     package: ./publish
